const { create } = require('xmlbuilder2')

const doc = create({ version: '1.0', encoding: 'UTF-8' })
	.ele('xml-stylesheet', {
		version: '2.0',
		type: 'text/xsl',
		href: '/api/xml/main-sitemap.xsl',
	})
	.ele('urlset', {
		'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
		'xmlns:image': 'http://www.google.com/schemas/sitemap-image/1.1',
		'xsi:schemaLocation':
			'http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd',
		xmlns: ' http://www.sitemaps.org/schemas/sitemap/0.9',
	})
	.ele('url')
	.ele('loc')
	.txt('http://localhost:8000/')
	.up()
	.ele('lastmod')
	.txt('22')
	.up()
	.ele('image:image')
	.ele('image:loc')
	.txt('https://victoriousseo.com/app/uploads/2020/12/Victorious_Share.png')
	.ele('image:title')
	.txt('Victorious_Share')
	.doc()

const printMe = doc.end({ prettyPrint: true })

export default function handler(req, res) {
	res.set('Content-Type', 'text/xml')
	res.send(printMe)
}

// 	<url>
// 		<loc>https://victoriousseo.com/</loc>
// 		<lastmod>2022-03-07T17:04:11+00:00</lastmod>
// 		<image:image>
// 			<image:loc>https://victoriousseo.com/app/uploads/2020/12/Victorious_Share.png</image:loc>
// 			<image:title>
// 				<![CDATA[Victorious_Share]]>
// 			</image:title>
// 		</image:image>
// 	</url>
// 	<url>
// 		<loc>https://victoriousseo.com/verticals/shopify-seo/</loc>
// 		<lastmod>2021-12-13T21:03:31+00:00</lastmod>
// 	</url>
// 	<url>
// 		<loc>https://victoriousseo.com/budget-for-seo-ebook/</loc>
// 		<lastmod>2022-02-07T22:11:55+00:00</lastmod>
// 		<image:image>
// 			<image:loc>https://victoriousseo.com/app/uploads/2021/03/vlad.jpg</image:loc>
// 		</image:image>
// 		<image:image>
// 			<image:loc>https://victoriousseo.com/app/uploads/2021/10/backlinks-elements.png</image:loc>
// 		</image:image>
// 		<image:image>
// 			<image:loc>https://victoriousseo.com/app/uploads/2021/07/tim.jpg</image:loc>
// 		</image:image>
// 	</url>
// </urlset>
// <!-- XML Sitemap generated by Yoast SEO -->

// <?xml version="1.0" encoding="UTF-8"?>
// <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
//         xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
//   <url>
//     <loc>http://example.com/sample1.html</loc>
//     <image:image>
//       <image:loc>http://example.com/image.jpg</image:loc>
//     </image:image>
//     <image:image>
//       <image:loc>http://example.com/photo.jpg</image:loc>
//     </image:image>
//   </url>
//   <url>
//     <loc>http://example.com/sample2.html</loc>
//     <image:image>
//       <image:loc>http://example.com/picture.jpg</image:loc>
//       <image:caption>A funny picture of a cat eating cabbage</image:caption>
//       <image:geo_location>Lyon, France</image:geo_location>
//       <image:title>Cat vs Cabbage</image:title>
//       <image:license>http://example.com/image-license</image:license>
//     </image:image>
//   </url>
// </urlset>
