const { create } = require('xmlbuilder2')

const doc = create({ version: '1.0', encoding: 'UTF-8' })
	.ins(
		'xml-stylesheet',
		`version="2.0"		type="text/xsl" href="/api/xml/main-sitemap.xsl"
	xmlns:html="http://www.w3.org/TR/REC-html40"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
	xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	`
	)
	.ele('xsl:output', {
		method: 'html',
		version: '1.0',
		encoding: ' UTF-8',
		indent: 'yes',
	})
	.ele('xsl:template', { match: '/' })
	.ele('html', { xmlns: 'http://www.w3.org/1999/xhtml' })
	.ele('head')
	.ele('title')
	.txt('Sitemap center')
	.ele('meta', {
		'http-equiv': 'Content-Type',
		content: 'text/html; charset=utf-8',
	})
	.ele('style', { type: 'text/css' })
	.txt(
		`body {
		font-family: Helvetica, Arial, sans-serif;
		font-size: 13px;
		color: #545353;
	}
	table {
		border: none;
		border-collapse: collapse;
	}
	#sitemap tr:nth-child(odd) td {
		background-color: #eee !important;
	}
	#sitemap tbody tr:hover td {
		background-color: #ccc;
	}
	#sitemap tbody tr:hover td, #sitemap tbody tr:hover td a {
		color: #000;
	}
	#content {
		margin: 0 auto;
		width: 1000px;
	}
	.expl {
		margin: 18px 3px;
		line-height: 1.2em;
	}
	.expl a {
		color: #da3114;
		font-weight: 600;
	}
	.expl a:visited {
		color: #da3114;
	}
	a {
		color: #000;
		text-decoration: none;
	}
	a:visited {
		color: #777;
	}
	a:hover {
		text-decoration: underline;
	}
	td {
		font-size:11px;
	}
	th {
		text-align:left;
		padding-right:30px;
		font-size:11px;
	}
	thead th {
		border-bottom: 1px solid #000;
	}`
	)
	.up()
	.up()
	.ele('body')
	.ele('div', { id: 'content' })
	.ele('h1')
	.txt('XML Sitemap')
	.ele('p')
	.txt('Generated by')
	.ele('a', {
		href: '/',
		target: '_blank',
		rel: 'noopener',
	})
	.txt('NÜktpls SEO')
	.up()
	.txt(
		`
this is an XML Sitemap, meant for consumption by search engines.

You can find more information about XML sitemaps on
<a href="" target="_blank" rel="noopener"></a>
	`
	)
	.ele('a', {
		href: 'https://sitemaps.org',
		target: '_blank',
		rel: 'noopener',
	})
	.txt('sitemaps.org')
	.up()
	.doc()

const printMe = doc.end({ prettyPrint: true })

export default function handler(req, res) {
	res.set('Content-Type', 'text/xml')
	res.send(printMe)
	// res.status(200).json(printMe)
}

// 					<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
// 						<p class="expl">
// 					This XML Sitemap Index file contains
// 							<xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps.

// 						</p>
// 						<table id="sitemap" cellpadding="3">
// 							<thead>
// 								<tr>
// 									<th width="75%">Sitemap</th>
// 									<th width="25%">Last Modified</th>
// 								</tr>
// 							</thead>
// 							<tbody>
// 								<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
// 									<xsl:variable name="sitemapURL">
// 										<xsl:value-of select="sitemap:loc"/>
// 									</xsl:variable>
// 									<tr>
// 										<td>
// 											<a href="{$sitemapURL}">
// 												<xsl:value-of select="sitemap:loc"/>
// 											</a>
// 										</td>
// 										<td>
// 											<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)),concat(' ', substring(sitemap:lastmod,20,6)))"/>
// 										</td>
// 									</tr>
// 								</xsl:for-each>
// 							</tbody>
// 						</table>
// 					</xsl:if>
// 					<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &lt; 1">
// 						<p class="expl">
// 					This XML Sitemap contains
// 							<xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.

// 						</p>
// 						<table id="sitemap" cellpadding="3">
// 							<thead>
// 								<tr>
// 									<th width="80%">URL</th>
// 									<th width="5%">Images</th>
// 									<th title="Last Modification Time" width="15%">Last Mod.</th>
// 								</tr>
// 							</thead>
// 							<tbody>
// 								<xsl:variable name="lower" select="'abcdefghijklmnopqrstuvwxyz'"/>
// 								<xsl:variable name="upper" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZ'"/>
// 								<xsl:for-each select="sitemap:urlset/sitemap:url">
// 									<tr>
// 										<td>
// 											<xsl:variable name="itemURL">
// 												<xsl:value-of select="sitemap:loc"/>
// 											</xsl:variable>
// 											<a href="{$itemURL}">
// 												<xsl:value-of select="sitemap:loc"/>
// 											</a>
// 										</td>
// 										<td>
// 											<xsl:value-of select="count(image:image)"/>
// 										</td>
// 										<td>
// 											<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)),concat(' ', substring(sitemap:lastmod,20,6)))"/>
// 										</td>
// 									</tr>
// 								</xsl:for-each>
// 							</tbody>
// 						</table>
// 					</xsl:if>
// 				</div>
// 			</body>
// 		</html>
// 	</xsl:template>
// </xsl:stylesheet>
